### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by srgskiri** [leoleovich/grafsy#3]
I would like to send some custom metrics to Grafsy so they would show up in Graphite but it doesn't work.

Graphite shows the grafsy metrics, so Grafsy can connect and send to Graphite.

I opened the "allowMetrics" to "^*" so it allows anything. But when I send some metric i.e.
(echo "my.metric 4 'date +%s'" | nc -q0 localhost 3002) it doesnt show up in Graphite.

The log file doesn't show anything except for "Server is running"

anything I am doing wrong?

**Comment by leoleovich** [comment]
Please try allowedMetrics = "^.*" and show me log entry of grafsy (by default log = "/var/log/grafsy/grafsy.log")

**Comment by srgskiri** [comment]
changed "allowedMetrics" to "^.*"
and the log file doesnt show anything:

> 2016/05/27 05:50:23.933207 server.go:175: Server is running

**Comment by leoleovich** [comment]
So did it help then?

**Comment by srgskiri** [comment]
Oh sorry, forgot to write the result. No, Graphite doesn't see my custom metrics, only Grafsy metrics

**Comment by leoleovich** [comment]
This issue is not related to ```allowedMetrics```.
Can you send metric like this:
```echo "my.metric 4 $(date +%s)" | nc  localhost 3002```

This works for me with setup of ```allowedMetrics = "^.*"```

**Comment by leoleovich** [comment]
If this metric got dropped by Grafsy, you would see the message in logs:
https://github.com/leoleovich/grafsy/blob/master/server.go#L128

**Comment by srgskiri** [comment]
Yes, that was it, thank you.

the date should have been written like this
> $(date +%s)
instead of this
> 'date +%s'

Im new to Linux, didn't know you could do that.

Tnx again, Grafsy is a great tool. It's nice it caches the metrics when graphite is down.

**Comment by leoleovich** [comment]
No problem :)
